# Generated by Django 4.2.11 on 2024-04-23 00:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('maximum_attendees', models.PositiveIntegerField()),
            ],
        ),
    ]
